name: "Action on issue open"
description: "create reposository on issue open event"
inputs:
  github-token:
    description: "Token"
    required: true
  repo-name:
    description: "Name for new repository"
    required: true
  org-owner:
    description: "Account name of organization owner"
    required: true
  contract-owner-acc:
    description: "Account id of contract owner"
    required: true
  type:
    description: "Type of issue"
    required: true
runs:
  using: "composite"
  steps:
    - name: Verify contract binary checksum against blockchain
      if: inputs.type == 'closed'
      run: |
        $GITHUB_ACTION_PATH/prepare.sh ${{ inputs.org-owner }} ${{ inputs.repo-name }}
        $GITHUB_ACTION_PATH/verify-contract.sh ${{ inputs.repo-name }} ${{ inputs.github-token }} ${{ inputs.org-owner }}
      shell: bash
    - name: Create new repository and invite collaborators
      if: inputs.type == 'opened'
      run: $GITHUB_ACTION_PATH/create-repository.sh ${{ inputs.github-token }} ${{ inputs.repo-name }} ${{ inputs.contract-owner-acc }} ${{ inputs.org-owner }}
      shell: bash
