name: "Action on issue open"
description: "create reposository on issue open event"
inputs:
  github-token:
    description: "Repository token"
    required: true
  github-privkey:
    description: "Github private key"
    required: true
  github-privkey-path:
    description: "Github private key path"
    required: true
  issue-repo-name:
    description: "Name for new repository"
    required: true
  org-owner:
    description: "Account name of organization owner"
    required: true
  issue-contract-owner-acc:
    description: "Account id of contract owner"
    required: true
  release-repo:
    description: "The repository on GitHub where the release created"
    required: true
  release-id:
    description: "Release ID"
    required: true
  issue-number:
    description: "Issue number"
    required: true
  type:
    description: "Type of issue"
    required: true
runs:
  using: "composite"
  steps:
    - name: Verify contract binary checksum against blockchain
      if: inputs.type == 'verify-checksum'
      run: |
        $GITHUB_ACTION_PATH/prepare.sh ${{ inputs.org-owner }} ${{ inputs.release-repo }}
        $GITHUB_ACTION_PATH/verify-contract.sh ${{ inputs.release-repo }} ${{ inputs.github-token }} ${{ inputs.org-owner }} ${{ inputs.release-id }} ${{ inputs.github-privkey }} ${{ inputs.github-privkey-path }}
      shell: bash
    - name: Create new repository and invite collaborators
      if: inputs.type == 'opened'
      run: $GITHUB_ACTION_PATH/create-repository.sh ${{ inputs.github-token }} ${{ inputs.issue-repo-name }} ${{ inputs.issue-contract-owner-acc }} ${{ inputs.org-owner }} ${{ inputs.issue-number }}
      shell: bash
