name: "Action on issue open"
description: "create reposository on issue open event"
inputs:
  github-token:
    description: "Token"
    required: true
  repo-name:
    description: "Name for new repository"
    required: true
  org-owner:
    description: "Account name of organization owner"
    required: true
  contract-owner-id:
    description: "Account name of contract owner"
    required: true
  runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/create-repository.sh ${{ inputs.github-token }} ${{ inputs.repo-name }} ${{ inputs.contract-owner-id }} ${{ inputs.org-owner }}
      shell: bash
