name: "On Issue Opened"
on:
  issues:
    types: [opened]

jobs:
  run:
    name: Run Bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          github-token: "${{ secrets.REPO_TOKEN }}"
          org-owner: "${{ vars.ORG_OWNER }}"
          repo-name: "${{ github.event.issue.title }}"
          contract-owner-id: "${{ github.event.issue.user.id }}"
