name: "On Issue Opened/CLosed"
on:
  issues:
    types: [opened]
  release:
    types: [published]

jobs:
  run:
    name: Verify contract source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          github-token: "${{ secrets.REPO_TOKEN }}"
          org-owner: "${{ vars.ORG_OWNER }}"
          type: "${{ github.event.action }}"
          issue-repo-name: "${{ github.event.issue.title }}"
          issue-contract-owner-acc: "${{ github.event.issue.user.login }}"
          issue-number: "${{ github.event.issue.number }}"
          release-repo: "${{ github.event.release.repository }}"
          release-id: "${{ github.event.release.release.id }}"
          release-name: "${{ github.event.release.release.name }}"
          release-tag-name: "${{ github.event.release.release.name }}"
