name: "Verify Contract"
on:
  repository_dispatch:
    types: [verify-checksum]

jobs:
  run:
    name: Verify contract source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Verify checksum
        id: verify
        uses: ./
        with:
          github-token: "${{ secrets.REPO_TOKEN }}"
          github-privkey: "${{ secrets.PRIV_KEY }}"
          github-privkey-path: "${{ secrets.PRIV_KEY_FILE }}"
          org-owner: "${{ vars.ORG_OWNER }}"
          type: "${{ github.event.action }}"
          release-repo: "${{ github.event.client_payload.Repository }}"
          release-id: "${{ github.event.client_payload.ReleaseID }}"
      - name: Notify valid repository
        id: slack-pass
        uses: slackapi/slack-github-action@v1.24.0
        if: ${{ steps.verify.outcome == 'success' }}; then
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}",
              "blocks": [
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
                    "text": "repository: *${{ github.event.client_payload.Repository }}*"
            			}
            		},
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
                    "text": "status: *verify passed* :tan-do2: :adet: :khang:"
            			}
            		},
                {
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
                    "text": "source_link: ${{ github.event.client_payload.SourceLink }}"
            			}
            		},
                {
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
                    "text": "workflow_link: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            			}
            		}
            	]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
      - name: Notify invalid repository
        if: ${{ steps.verify.outcome != 'success' }}
        id: slack-fail
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}",
              "blocks": [
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
                    "text": "repository: *${{ github.event.client_payload.Repository }}*"
            			}
            		},
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
                    "text": "status: *verify failed* :mai_do:"
            			}
            		},
                {
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
                    "text": "source_link: ${{ github.event.client_payload.SourceLink }}"
            			}
            		},
                {
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
                    "text": "workflow_link: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            			}
            		}
            	]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
