name: "Verify Contract"
on:
  repository_dispatch:
    types: [verify-checksum]

jobs:
  run:
    name: Verify contract source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # - name: Verify checksum
      #   uses: ./
      #   with:
      #     github-token: "${{ secrets.REPO_TOKEN }}"
      #     github-privkey: "${{ secrets.PRIV_KEY }}"
      #     github-privkey-path: "${{ secrets.PRIV_KEY_FILE }}"
      #     org-owner: "${{ vars.ORG_OWNER }}"
      #     type: "${{ github.event.action }}"
      #     release-repo: "${{ github.event.client_payload.Repository }}"
      #     release-id: "${{ github.event.client_payload.ReleaseID }}"
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}",
              "blocks": [
                {
                  "type": "repository"
                  "text: "repository: ${{ github.event.client_payload.Repository }}",
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
