name: "Verify Contract"
on:
  repository_dispatch:
    types: [verify-checksum]

jobs:
  run:
    name: Verify contract source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          github-token: "${{ secrets.REPO_TOKEN }}"
          github-privkey: "${{ secrets.PRIV_KEY }}"
          org-owner: "${{ vars.ORG_OWNER }}"
          type: "${{ github.event.action }}"
          release-repo: "${{ github.event.client_payload.repository }}"
          release-id: "${{ github.event.client_payload.releaseid }}"
          release-tag-name: "${{ github.event.client_payload.tagname }}"
