name: "Verify Contract"
on:
  repository_dispatch:
    types: [verify-checksum]

jobs:
  run:
    name: Verify contract source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Verify checksum
        id: verify
        uses: ./
        run: echo 'okoko'
      #   with:
      #     github-token: "${{ secrets.REPO_TOKEN }}"
      #     github-privkey: "${{ secrets.PRIV_KEY }}"
      #     github-privkey-path: "${{ secrets.PRIV_KEY_FILE }}"
      #     org-owner: "${{ vars.ORG_OWNER }}"
      #     type: "${{ github.event.action }}"
      #     release-repo: "${{ github.event.client_payload.Repository }}"
      #     release-id: "${{ github.event.client_payload.ReleaseID }}"
      - name: Notify valid repository
        if: ${{ job.steps.verify.conclusion == 'success' }}
        id: slack-pass
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
                    "text": "repository: *${{ github.event.client_payload.Repository }}*"
            			}
            		},
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
                    "text": "status: *verify passed*"
            			}
            		},
                {
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
                    "text": "source_link: ${{ github.event.client_payload.SourceLink }} :adet: :tan-do2: :khang:"
            			}
            		}
            	]
            }
      - name: Notify invalid repository
        if: ${{ job.steps.verify.conclusion != 'success' }}
        id: slack-fail
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
                    "text": "repository: *${{ github.event.client_payload.Repository }}*"
            			}
            		},
            		{
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
                    "text": "status: *verify failed*"
            			}
            		},
                {
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
                    "text": "source_link: ${{ github.event.client_payload.SourceLink }} :mai_do:"
            			}
            		}
            	]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
